Реализовал функционал для TasksController, TaskCategories
eniluck/Pomodoro pull request #1
Opened 2022-04-14 17:05 UTC by eniluck

2022-04-17 08:05 UTC, pingvin1308 commented on Pomodoro.Api/Contracts/Requests/Task/TaskCategoryRequest.cs
>      public class TaskCategoryRequest
TaskCategoryRequest -> GetTaskCategoryRequest
-> GetCategoryRequest

2022-04-17 08:05 UTC, pingvin1308 commented on Pomodoro.Api/Contracts/Requests/Task/UpdateTaskRequest.cs
>          public int Id { get; set; }
public int Id { get; set; }
можно убрать

2022-04-17 08:05 UTC, pingvin1308 commented on Pomodoro.Api/Contracts/Requests/Task/UpdateTaskRequest.cs
>          public int Id { get; set; }
PUT /api/tasks/{taskId}

public async Task<IActionResult>([FromRoute] int taskId, [FromBody] UpdateTaskRequest request)

2022-04-17 08:05 UTC, pingvin1308 commented on Pomodoro.Api/Contracts/Requests/Task/UpdateTaskRequest.cs
> +        public TaskStatusRequest Status { get; set; }
TaskStatusRequest - можно тащить из домена

2022-04-17 08:05 UTC, pingvin1308 commented on Pomodoro.Api/Contracts/Responses/Task/TaskCategoryResponse.cs
>      public class TaskCategoryResponse
TaskCategoryResponse -> GetTaskCategoryResponse

2022-04-17 08:05 UTC, pingvin1308 commented on Pomodoro.Api/Contracts/Responses/Task/TaskResponse.cs
>      public class TaskResponse
TaskResponse -> GetTaskResponse

2022-04-17 08:05 UTC, pingvin1308 commented on Pomodoro.Api/Controllers/TaskCategoriesController.cs
> +        public TaskCategoriesController(ILogger<TaskCategoriesController> logger, IMapper mapper, ITaskCategoriesService taskCategoriesService)
public TaskCategoriesController(
    ILogger<TaskCategoriesController> logger, 
    IMapper mapper, 
    ITaskCategoriesService taskCategoriesService)

2022-04-17 08:05 UTC, pingvin1308 commented on Pomodoro.Api/Controllers/TaskCategoriesController.cs
> +            return Ok(_mapper.Map<TaskCategoryResponse>(createdCategory));
Для занятия:
Попробовать воспроизвести ошибки с маппингом (указание конкретного типа при маппинге)

2022-04-17 08:05 UTC, pingvin1308 commented on Pomodoro.Api/Controllers/TaskCategoriesController.cs
>          [HttpGet("GetAllCategories")]
GetAllCategories -> GET TaskCategories

2022-04-17 08:05 UTC, pingvin1308 commented on Pomodoro.Api/Controllers/TaskCategoriesController.cs
>          [HttpPost("AddCategory")]
AddCategory -> POST TaskCategories

2022-04-17 08:05 UTC, pingvin1308 commented on Pomodoro.Api/Controllers/TaskCategoriesController.cs
>          [HttpPut("UpdateCategory")]
UpdateCategory -> PUT TaskCategories/{taskId:int}

2022-04-17 08:05 UTC, pingvin1308 commented on Pomodoro.Api/Controllers/TaskCategoriesController.cs
>              var request = _mapper.Map<TaskCategory>(categoryRequest);
убрать лишний маппинг

2022-04-17 08:05 UTC, pingvin1308 commented on Pomodoro.DAL.Postgres/Entities/TaskEntity.cs
>          public string? Name { get; set; }
Name - является обязательным параметром
убрать ?

2022-04-17 08:05 UTC, pingvin1308 commented on Pomodoro.Core/ITaskRepository.cs
> +        Task<List<TaskModel>> GetAllAsync();
лучше вернуть [] вместо List

2022-04-17 08:05 UTC, pingvin1308 commented on Pomodoro.Api/MappingProfle.cs
> +            CreateMap<CreateTaskRequest, TaskModel>();
CreateMap<CreateTaskRequest, TaskModel>();

2022-04-17 08:05 UTC, pingvin1308 commented on Pomodoro.Api/MappingProfle.cs
> +            CreateMap<CreateTaskRequest, TaskModel>();
CreateMap<UpdateTaskRequest, TaskModel>();
можно убрать, так как у тебя все проходит через Create метод

2022-04-18 12:06 UTC, eniluck commented on Pomodoro.Api/Contracts/Requests/Task/TaskCategoryRequest.cs
>      public class TaskCategoryRequest
Переименовал контрактные модели с префиксами Create и Put. Теперь так выглядит: 

- CreateCategoryRequest
- PutCategoryRequest
- CreateTaskRequest
- PutTaskRequest

2022-04-18 12:10 UTC, eniluck commented on Pomodoro.Api/Contracts/Requests/Task/UpdateTaskRequest.cs
>          public int Id { get; set; }
сделал.

2022-04-18 12:10 UTC, eniluck commented on Pomodoro.Api/Contracts/Requests/Task/UpdateTaskRequest.cs
> +        public TaskStatusRequest Status { get; set; }
Сделал.

2022-04-18 12:15 UTC, eniluck commented on Pomodoro.Api/Contracts/Responses/Task/TaskCategoryResponse.cs
>      public class TaskCategoryResponse
сделал.

2022-04-18 12:17 UTC, eniluck commented on Pomodoro.Api/Contracts/Responses/Task/TaskResponse.cs
>      public class TaskResponse
Сделал. Но. вопрос по контрактной модельке: 
GetTaskResponse в себе содержит поле типа  GetCategoryResponse. Которое так же возвращается контроллером TaskCategoriesController. 
Оставить как есть или нужно сразу контракты отделять друг от друга во избежание путаницы в бедующем ?

2022-04-18 12:22 UTC, eniluck commented on Pomodoro.Api/Controllers/TaskCategoriesController.cs
> +        public TaskCategoriesController(ILogger<TaskCategoriesController> logger, IMapper mapper, ITaskCategoriesService taskCategoriesService)
поправил форматирование.

2022-04-18 12:37 UTC, eniluck commented on Pomodoro.Api/Controllers/TaskCategoriesController.cs
> +            return Ok(_mapper.Map<TaskCategoryResponse>(createdCategory));
Заменил методы Map в коде принимающие объект в качестве параметра на метод generic Map который принимает параметр типа TSource. 

было
TDestination Map<TDestination>(object source);
стало
TDestination Map<TSource, TDestination>(TSource source);

2022-04-18 12:47 UTC, eniluck commented on Pomodoro.Api/Controllers/TaskCategoriesController.cs
>          [HttpGet("GetAllCategories")]
сделал как тут написано: https://restfulapi.net/resource-naming/

2022-04-18 12:47 UTC, eniluck commented on Pomodoro.Api/Controllers/TaskCategoriesController.cs
>          [HttpPost("AddCategory")]
сделал.

2022-04-18 12:47 UTC, eniluck commented on Pomodoro.Api/Controllers/TaskCategoriesController.cs
>          [HttpPut("UpdateCategory")]
сделал.

2022-04-18 12:57 UTC, eniluck commented on Pomodoro.Api/Controllers/TaskCategoriesController.cs
>              var request = _mapper.Map<TaskCategory>(categoryRequest);
убрал.

2022-04-18 13:04 UTC, eniluck commented on Pomodoro.DAL.Postgres/Entities/TaskEntity.cs
>          public string? Name { get; set; }
сделал. миграции добавил.

2022-04-18 13:11 UTC, eniluck commented on Pomodoro.Core/ITaskRepository.cs
> +        Task<List<TaskModel>> GetAllAsync();
сделано.

2022-04-18 13:18 UTC, eniluck commented on Pomodoro.Api/MappingProfle.cs
> +            CreateMap<CreateTaskRequest, TaskModel>();
убрал.

2022-04-24 07:26 UTC, pingvin1308 requested changes

2022-04-24 07:26 UTC, pingvin1308 commented on Pomodoro.Api/Contracts/Requests/Category/CreateCategoryRequest.cs
> +        public string Name { get; set; } = string.Empty;
Можно еще задать ограничения по длине строки :)

2022-04-24 07:26 UTC, pingvin1308 commented on Pomodoro.Api/Controllers/CategoriesController.cs
> +    [ApiController]
Produces
Consumes

2022-04-24 07:26 UTC, pingvin1308 commented on Pomodoro.Api/Controllers/CategoriesController.cs
> +        [ProducesResponseType(typeof(string[]), StatusCodes.Status400BadRequest)]
ProblemDetails

2022-04-24 07:26 UTC, pingvin1308 commented on Pomodoro.Api/Controllers/CategoriesController.cs
> +        [HttpPut("{id:int}")]
id -> categoryId

2022-04-24 07:26 UTC, pingvin1308 commented on Pomodoro.Api/Controllers/CategoriesController.cs
> +        public async Task<IActionResult> UpdateCategory([FromRoute]int id, [FromBody]PutCategoryRequest putCategoryRequest)
```C#
public async Task<Result> UpdateTaskAsync(int taskId, TaskCategory taskToUpdate)
        {
            var task = await _taskCategoryRepository.GetAsync(taskId);
            if (task is null)
            {
                return Result.Failure("Not found task");
            }
            
            var updatedTask = taskToUpdate with { Id = task.Id }; 

            await _taskCategoryRepository.UpdateAsync(updatedtask);
        }
```

2022-04-24 07:26 UTC, pingvin1308 commented on Pomodoro.Api/appsettings.Tests.json
> +    "PomodoroConnection": "Host=localhost;Port=5432;Database=PomodoroTest;Username=postgres;Password=postgres"
"PomodoroConnection": "<your connection string>"

user secrets -> dotnet, docker

2022-04-24 07:26 UTC, pingvin1308 commented on Pomodoro.BL/TaskService.cs
> +                    var error = new string[] { "Не найдена категория по Id" };
Создать класс с ошибками

2022-04-24 07:26 UTC, pingvin1308 commented on Pomodoro.Core/Models/TaskCategory.cs
> +        public string? Name { get; }
Name не может быть опциональным :)

2022-05-07 16:42 UTC, eniluck commented on Pomodoro.Api/Contracts/Requests/Category/CreateCategoryRequest.cs
> +        public string Name { get; set; } = string.Empty;
CreateCategoryRequest, PutCategoryRequest, CreateTaskRequest, PutTaskRequest добавил атрибут MaxLength.
Пока думал сколько длина символов должна быть, пришло осоздание что в бд так же хранится без размера строка. Изменил длину в этом слое. за одно настроил fluent-api для конфигурации сущностей. ну и добавил миграцию.
**Здесь вопрос по длине строке в BL слое. Можно использовать FluentValidator библиотеку или решать через доменную модель?**

2022-05-07 17:12 UTC, eniluck commented on Pomodoro.Api/Controllers/CategoriesController.cs
> +    [ApiController]
Добавил Consumes атрибут.

2022-05-07 17:14 UTC, eniluck commented on Pomodoro.Core/Models/TaskCategory.cs
> +        public string? Name { get; }
поправил.

2022-05-08 08:14 UTC, eniluck commented on Pomodoro.Api/Controllers/CategoriesController.cs
> +        [HttpPut("{id:int}")]
сделал.

2022-05-09 02:34 UTC, pingvin1308 requested changes

2022-05-09 02:34 UTC, pingvin1308 commented on Pomodoro.Core/Models/TaskCategory.cs
> +        public static (TaskCategory? Result, string[] Errors) Create(int id, string name)
Скорее всего метод Create с параметром id не нужен.
Объект класса TaskCategory восстанавливается из БД через automapper

2022-05-09 02:34 UTC, pingvin1308 commented on Pomodoro.Core/Models/TaskCategory.cs
>      {
public const string MAX_NAME_LENGTH = 100;

2022-05-09 02:34 UTC, pingvin1308 commented on Pomodoro.DAL.Postgres/Configurations/TaskConfiguration.cs
> +            .HasMaxLength(1024);
Вынести число в константу

2022-05-09 02:34 UTC, pingvin1308 commented on Pomodoro.DAL.Postgres/Configurations/TaskConfiguration.cs
> +            .HasMaxLength(1024);
Для проверки валидности строки, которая приходит из БД, можно добавить 
HasConvertion(x => x, x => {  if(noValid) throw Exception(""); })

2022-05-11 16:44 UTC, eniluck commented on Pomodoro.Core/Models/TaskCategory.cs
> +        public static (TaskCategory? Result, string[] Errors) Create(int id, string name)
изменил.

2022-05-11 16:58 UTC, eniluck commented on Pomodoro.Core/Models/TaskCategory.cs
>      {
сделал.

2022-05-11 16:59 UTC, eniluck commented on Pomodoro.DAL.Postgres/Configurations/TaskConfiguration.cs
> +            .HasMaxLength(1024);
сделал

2022-05-15 06:36 UTC, pingvin1308 approved these changes

2022-05-15 06:36 UTC, pingvin1308 commented on Pomodoro.Api/Contracts/Requests/Category/CreateCategoryRequest.cs
> +        public string Name { get; set; } = string.Empty;
первый шаг по рефакторингу валидации - это сделать отдельный метод Validate.

затем можно использовать библиотеки, для упрощения написания валидации

2022-05-15 06:36 UTC, pingvin1308 commented on Pomodoro.Api/Contracts/Requests/Category/UpdateCategoryRequest.cs
> +    {
public UpdateCategoryRequest(string name)
{
    Name = name;
}

2022-05-15 06:36 UTC, pingvin1308 commented on Pomodoro.Api/Controllers/CategoriesController.cs
> +    [ApiController]
[Consumes("application/json")] -> [Consumes(MediaTypeNames.Application.Json)]
[Produces("application/json")] -> [Produces(MediaTypeNames.Application.Json)]

2022-05-15 06:36 UTC, pingvin1308 commented on Pomodoro.DAL.Postgres/Configurations/TaskCategoryConfiguration.cs
> +        builder.ToTable("TaskCategory");
TaskCategory -> TaskCategories
но тут достаточно просто убрать ToTable и позволить ef сгенерить название

2022-05-16 16:13 UTC, eniluck commented on Pomodoro.Api/Controllers/CategoriesController.cs
> +    [ApiController]
перенёс для контроллера эти атрибуты.

2022-05-17 17:09 UTC, eniluck commented on Pomodoro.Api/Contracts/Requests/Category/UpdateCategoryRequest.cs
> +    {
сделал.

2022-05-17 17:09 UTC, eniluck commented on Pomodoro.DAL.Postgres/Configurations/TaskCategoryConfiguration.cs
> +        builder.ToTable("TaskCategory");
сделал.

2022-05-17 17:13 UTC, merged